[build]
# This default build command adds the robots noindex directive to the site headers.
# It is turned off for only for the production site by using [context.master] below
# DO NOT REMOVE THIS
publish = "docs/public"
functions = "functions"
command = "cd docs && make non-production-build"

[build.environment]
HUGO_VERSION = "0.49"

[context.production.environment]
HUGO_BASEURL = "https://docs.docksal.io/"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "cd docs && hugo --enableGitInfo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "cd docs && hugo --enableGitInfo -b $DEPLOY_PRIME_URL"

[context.master]
# This context is triggered by the `master` branch and allows search indexing
# DO NOT REMOVE THIS (contact @chenopis or @sig-docs-maintainers)
publish = "docs/public"
command = "cd docs && make production-build"
