title = "Docksal Documentation"
languageCode = "en-us"
theme = "docksal-docs"

[params]
  description = "Official Docksal documentation website"
  editURL = "https://github.com/docksal/docksal/edit/master/docs/"
